version: '3.8'
services:
  api-server:
    image: user-admin:1.0
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - auth-network
    container_name: api-con

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - auth-network
    volumes:
      - mongo-data:/data/db
    container_name: mongo-con

networks:
  auth-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local