version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: auth-admin
    hostname: mongo
    volumes:
      - mongo:/data/db
    restart:
      always
    networks:
      - auth-network
    ports: 
      - 27017:27017
  app:
    build : .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    networks:
      - auth-network        
networks:
  auth-network:
volumes:
  mongo: